apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: evaluate-the-coco-based-model-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.1, pipelines.kubeflow.org/pipeline_compilation_time: '2020-11-16T11:56:28.597087',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Evaluate the COCO based
      model", "inputs": [{"default": "unitytechnologies/datasetinsights:latest", "name":
      "docker", "optional": true, "type": "String"}, {"default": "gs://thea-dev/data/coco_cat/val2017.zip",
      "name": "source_uri", "optional": true, "type": "String"}, {"default": "gs://thea-dev/data/coco_cat/annotations_trainval2017.zip",
      "name": "ann_uri", "optional": true, "type": "String"}, {"default": "datasetinsights/configs/faster_rcnn_coco_cat.yaml",
      "name": "config", "optional": true, "type": "String"}, {"default": "gs://<bucket>/checkpoints/yyyymmdd-hhmm",
      "name": "checkpoint_file", "optional": true, "type": "String"}, {"default":
      "gs://<bucket>/runs/yyyymmdd-hhmm", "name": "tb_log_dir", "optional": true,
      "type": "String"}, {"default": "50Gi", "name": "volume_size", "optional": true,
      "type": "String"}], "name": "Evaluate the COCO based model"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.1}
spec:
  entrypoint: evaluate-the-coco-based-model
  templates:
  - name: download
    container:
      args: ['--source-uri={{inputs.parameters.source_uri}}', --output=/data, --include-binary]
      command: [datasetinsights, download]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/user-gcp-sa.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/user-gcp-sa.json}
      image: '{{inputs.parameters.docker}}'
      resources:
        limits: {memory: 64Gi}
        requests: {memory: 64Gi}
      volumeMounts:
      - {mountPath: /data, name: pvc}
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-user-gcp-sa}
    inputs:
      parameters:
      - {name: docker}
      - {name: pvc-name}
      - {name: source_uri}
    volumes:
    - name: gcp-credentials-user-gcp-sa
      secret: {secretName: user-gcp-sa}
    - name: pvc
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pvc-name}}'}
  - name: download-2
    container:
      args: ['--source-uri={{inputs.parameters.ann_uri}}', --output=/data, --include-binary]
      command: [datasetinsights, download]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/user-gcp-sa.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/user-gcp-sa.json}
      image: '{{inputs.parameters.docker}}'
      resources:
        limits: {memory: 64Gi}
        requests: {memory: 64Gi}
      volumeMounts:
      - {mountPath: /data, name: pvc}
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-user-gcp-sa}
    inputs:
      parameters:
      - {name: ann_uri}
      - {name: docker}
      - {name: pvc-name}
    volumes:
    - name: gcp-credentials-user-gcp-sa
      secret: {secretName: user-gcp-sa}
    - name: pvc
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pvc-name}}'}
  - name: evaluate
    container:
      args: ['--config={{inputs.parameters.config}}', '--checkpoint-file={{inputs.parameters.checkpoint_file}}',
        --test-data=/data, '--tb-log-dir={{inputs.parameters.tb_log_dir}}', --kfp-log-dir=/kfp_logs,
        --kfp-ui-metadata-filename=kfp_ui_metadata.json, --kfp-metrics-filename=kfp_metrics.json]
      command: [datasetinsights, evaluate]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/user-gcp-sa.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/user-gcp-sa.json}
      image: '{{inputs.parameters.docker}}'
      resources:
        limits: {nvidia.com/gpu: 1, memory: 64Gi}
        requests: {memory: 64Gi}
      volumeMounts:
      - {mountPath: /data, name: pvc}
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-user-gcp-sa}
    inputs:
      parameters:
      - {name: checkpoint_file}
      - {name: config}
      - {name: docker}
      - {name: pvc-name}
      - {name: tb_log_dir}
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path: /kfp_logs/kfp_metrics.json}
      - {name: mlpipeline-ui-metadata, path: /kfp_logs/kfp_ui_metadata.json}
    nodeSelector: {cloud.google.com/gke-accelerator: nvidia-tesla-v100}
    volumes:
    - name: gcp-credentials-user-gcp-sa
      secret: {secretName: user-gcp-sa}
    - name: pvc
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pvc-name}}'}
  - name: evaluate-the-coco-based-model
    inputs:
      parameters:
      - {name: ann_uri}
      - {name: checkpoint_file}
      - {name: config}
      - {name: docker}
      - {name: source_uri}
      - {name: tb_log_dir}
      - {name: volume_size}
    dag:
      tasks:
      - name: download
        template: download
        dependencies: [pvc]
        arguments:
          parameters:
          - {name: docker, value: '{{inputs.parameters.docker}}'}
          - {name: pvc-name, value: '{{tasks.pvc.outputs.parameters.pvc-name}}'}
          - {name: source_uri, value: '{{inputs.parameters.source_uri}}'}
      - name: download-2
        template: download-2
        dependencies: [download, pvc]
        arguments:
          parameters:
          - {name: ann_uri, value: '{{inputs.parameters.ann_uri}}'}
          - {name: docker, value: '{{inputs.parameters.docker}}'}
          - {name: pvc-name, value: '{{tasks.pvc.outputs.parameters.pvc-name}}'}
      - name: evaluate
        template: evaluate
        dependencies: [download-2, pvc]
        arguments:
          parameters:
          - {name: checkpoint_file, value: '{{inputs.parameters.checkpoint_file}}'}
          - {name: config, value: '{{inputs.parameters.config}}'}
          - {name: docker, value: '{{inputs.parameters.docker}}'}
          - {name: pvc-name, value: '{{tasks.pvc.outputs.parameters.pvc-name}}'}
          - {name: tb_log_dir, value: '{{inputs.parameters.tb_log_dir}}'}
      - name: pvc
        template: pvc
        arguments:
          parameters:
          - {name: volume_size, value: '{{inputs.parameters.volume_size}}'}
  - name: pvc
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.name}}-pvc'
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: '{{inputs.parameters.volume_size}}'
    inputs:
      parameters:
      - {name: volume_size}
    outputs:
      parameters:
      - name: pvc-manifest
        valueFrom: {jsonPath: '{}'}
      - name: pvc-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: pvc-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
  arguments:
    parameters:
    - {name: docker, value: 'unitytechnologies/datasetinsights:latest'}
    - {name: source_uri, value: 'gs://thea-dev/data/coco_cat/val2017.zip'}
    - {name: ann_uri, value: 'gs://thea-dev/data/coco_cat/annotations_trainval2017.zip'}
    - {name: config, value: datasetinsights/configs/faster_rcnn_coco_cat.yaml}
    - {name: checkpoint_file, value: 'gs://<bucket>/checkpoints/yyyymmdd-hhmm'}
    - {name: tb_log_dir, value: 'gs://<bucket>/runs/yyyymmdd-hhmm'}
    - {name: volume_size, value: 50Gi}
  serviceAccountName: pipeline-runner
