name: Scan branch and pull requests using SonarQube

on:
  push:
  pull_request:

jobs:
  sonar-scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: ut-logs
          path: logs
      - run: echo "SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)" >> $GITHUB_ENV
      - if: ${{ github.event_name != 'pull_request' }}
        run: sonar-scanner
          -Dsonar.host.url=https://sonarqube.internal.unity3d.com
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
          -Dsonar.qualitygate.wait=true
          -Dsonar.projectVersion=${{ env.SHA_SHORT }}
          -Dsonar.branch.name=${{ github.REF_NAME }}
      - if: ${{ github.event_name == 'pull_request' }}
        run: sonar-scanner
          -Dsonar.host.url=https://sonarqube.internal.unity3d.com
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
          -Dsonar.qualitygate.wait=true
          -Dsonar.projectVersion=${{ env.SHA_SHORT }}
          -Dsonar.pullrequest.key=${{ github.event.number }}
          -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
          -Dsonar.pullrequest.base=${{ github.BASE_REF }}
